language: ruby
rvm:
  - 2.7.1
cache:
  - bundler
  - yarn
services:
  - postgresql
before_install:
  - nvm install --lts
before_script:
  - bundle exec rails db:create
  - bundle exec rails db:migrate
script: bundle exec rspec spec

